32 vistainstructor
joseocio192/Club-Conquistadores pull request #39
Opened 2024-05-10 07:54 UTC by joseocio192

2024-05-10 07:58 UTC, joseocio192 commented
@gatoguapo te toca hacerlo bonito

2024-05-10 08:52 UTC, joseocio192 commented
![image](https://github.com/joseocio192/Club-Conquistadores/assets/53511945/ed1bb155-fbf0-4d60-a503-b34cbdc7bc24)

2024-05-11 00:31 UTC, luischang07 requested changes

2024-05-11 00:31 UTC, luischang07 commented on resources/js/RegisterView.jsx
ctm

2024-05-11 00:31 UTC, luischang07 commented on routes/web.php
tremendo cochinero

2024-05-11 00:51 UTC, joseocio192 commented on app/Http/Controllers/InstructorController.php
> +    public function crearClase(Request $request)
@luischang07 claro que si

2024-05-12 08:18 UTC, joseocio192 commented
Vista clase 
![image](https://github.com/joseocio192/Club-Conquistadores/assets/53511945/8f4e9310-e275-43e2-8094-61456a09c3d2)
Vista Gestionar clase 
![image](https://github.com/joseocio192/Club-Conquistadores/assets/53511945/afa1f2dc-f63d-4ebc-9a5d-7c6082b8003d)
Vista default 
![image](https://github.com/joseocio192/Club-Conquistadores/assets/53511945/c143241c-8147-4fd8-9782-175900867165)
Vista tarea al hacer click en alguna tarea
![image](https://github.com/joseocio192/Club-Conquistadores/assets/53511945/421af431-5198-4e87-af8c-a3b6f86abc6f)
Vista conquistador al hacer click en el en alguna clase
![image](https://github.com/joseocio192/Club-Conquistadores/assets/53511945/18e5c36a-3d74-456c-b13f-a920f589b190)

2024-05-17 19:18 UTC, closed without merging